# Autonomous Business System Configuration
# LoanFlow Personal Loan Management System
# Main Configuration File

# Application Settings
app:
  name: "LoanFlow Autonomous Business System"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  debug: true
  host: "0.0.0.0"
  port: 5000
  secret_key: "your-secret-key-here-change-in-production"
  timezone: "UTC"
  language: "en"
  
# Database Configuration
database:
  # Primary Database (MySQL)
  primary:
    type: "mysql"
    host: "localhost"
    port: 3306
    name: "loanflow_autonomous"
    username: "loanflow_user"
    password: "secure_password_123"
    charset: "utf8mb4"
    pool_size: 20
    max_overflow: 30
    pool_timeout: 30
    pool_recycle: 3600
    echo: false
    
  # Backup Database (PostgreSQL)
  backup:
    type: "postgresql"
    host: "localhost"
    port: 5432
    name: "loanflow_backup"
    username: "postgres"
    password: "backup_password_456"
    
  # MongoDB for Document Storage
  document_store:
    type: "mongodb"
    host: "localhost"
    port: 27017
    name: "loanflow_documents"
    username: "mongo_user"
    password: "mongo_password_789"

# Redis Configuration
redis:
  # Main Redis Instance
  main:
    host: "localhost"
    port: 6379
    db: 0
    password: null
    socket_timeout: 5
    socket_connect_timeout: 5
    socket_keepalive: true
    socket_keepalive_options: {}
    connection_pool_kwargs: {}
    max_connections: 50
    
  # Cache Redis Instance
  cache:
    host: "localhost"
    port: 6379
    db: 1
    password: null
    default_timeout: 3600
    
  # Session Redis Instance
  session:
    host: "localhost"
    port: 6379
    db: 2
    password: null
    
  # Queue Redis Instance
  queue:
    host: "localhost"
    port: 6379
    db: 3
    password: null

# AI Services Configuration
ai_services:
  # OpenAI Configuration
  openai:
    api_key: "your-openai-api-key-here"
    model: "gpt-4"
    max_tokens: 4000
    temperature: 0.7
    timeout: 30
    
  # Machine Learning Models
  ml_models:
    risk_assessment:
      model_path: "models/risk_assessment_model.pkl"
      threshold: 0.7
      
    fraud_detection:
      model_path: "models/fraud_detection_model.pkl"
      threshold: 0.8
      
    credit_scoring:
      model_path: "models/credit_scoring_model.pkl"
      features: ["income", "credit_history", "debt_ratio", "employment_length"]
      
  # Natural Language Processing
  nlp:
    sentiment_analysis:
      model: "textblob"
      
    content_generation:
      model: "openai"
      templates_path: "templates/content/"

# Security Configuration
security:
  # JWT Settings
  jwt:
    secret_key: "jwt-secret-key-change-in-production"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
    
  # Password Settings
  password:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    hash_algorithm: "argon2"
    
  # Rate Limiting
  rate_limiting:
    enabled: true
    default_limit: "100 per hour"
    login_limit: "5 per minute"
    api_limit: "1000 per hour"
    
  # CORS Settings
  cors:
    origins: ["http://localhost:3000", "https://yourdomain.com"]
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization"]
    
  # SSL/TLS Settings
  ssl:
    enabled: false
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"

# Email Configuration
email:
  # SMTP Settings
  smtp:
    server: "smtp.gmail.com"
    port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    use_tls: true
    use_ssl: false
    
  # Email Templates
  templates:
    path: "templates/email/"
    default_sender: "noreply@loanflow.com"
    
  # Email Queues
  queues:
    high_priority: "email_high"
    normal_priority: "email_normal"
    low_priority: "email_low"

# Payment Gateway Configuration
payment:
  # Stripe Configuration
  stripe:
    publishable_key: "pk_test_your_stripe_publishable_key"
    secret_key: "sk_test_your_stripe_secret_key"
    webhook_secret: "whsec_your_webhook_secret"
    
  # PayPal Configuration
  paypal:
    client_id: "your_paypal_client_id"
    client_secret: "your_paypal_client_secret"
    mode: "sandbox"  # sandbox or live
    
  # Bank Integration
  banking:
    plaid:
      client_id: "your_plaid_client_id"
      secret: "your_plaid_secret"
      environment: "sandbox"  # sandbox, development, production

# Monitoring and Logging
monitoring:
  # Logging Configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file_path: "logs/autonomous_system.log"
    max_file_size: "10MB"
    backup_count: 5
    
  # Metrics Collection
  metrics:
    enabled: true
    prometheus:
      enabled: true
      port: 9090
      
  # Health Checks
  health_checks:
    enabled: true
    interval: 60  # seconds
    endpoints:
      - "/health"
      - "/health/database"
      - "/health/redis"
      - "/health/ai-services"
      
  # Alerting
  alerts:
    enabled: true
    email_recipients: ["admin@loanflow.com"]
    slack_webhook: "https://hooks.slack.com/your-webhook-url"
    
# Business Logic Configuration
business:
  # Loan Processing
  loans:
    min_amount: 1000
    max_amount: 50000
    min_term_months: 6
    max_term_months: 60
    interest_rate_range: [5.0, 25.0]
    processing_fee_percentage: 2.5
    
  # Risk Assessment
  risk:
    credit_score_minimum: 600
    debt_to_income_max: 0.4
    employment_minimum_months: 6
    
  # Automated Decisions
  automation:
    auto_approve_threshold: 0.9
    auto_reject_threshold: 0.3
    manual_review_range: [0.3, 0.9]
    
# SEO and Marketing Configuration
seo:
  # Keyword Research
  keywords:
    primary: ["personal loans", "quick loans", "online lending"]
    secondary: ["bad credit loans", "debt consolidation", "emergency loans"]
    
  # Content Generation
  content:
    blog_frequency: "daily"
    social_media_frequency: "hourly"
    
  # Backlink Strategy
  backlinks:
    target_domains: ["finance.yahoo.com", "nerdwallet.com", "creditkarma.com"]
    monthly_target: 50
    
# Performance Configuration
performance:
  # Caching
  cache:
    default_timeout: 3600
    long_timeout: 86400
    short_timeout: 300
    
  # Database Optimization
  database_optimization:
    query_timeout: 30
    connection_timeout: 10
    slow_query_threshold: 1.0
    
  # Background Tasks
  background_tasks:
    max_workers: 4
    queue_timeout: 300
    
# Feature Flags
feature_flags:
  autonomous_loan_processing: true
  ai_customer_service: true
  automated_seo: true
  fraud_detection: true
  risk_assessment: true
  document_generation: true
  email_automation: true
  payment_processing: true
  business_intelligence: true
  mobile_api: false
  
# Development Settings
development:
  # Debug Settings
  debug:
    sql_echo: false
    profiling: false
    
  # Testing
  testing:
    database_url: "sqlite:///test.db"
    redis_url: "redis://localhost:6379/15"
    
# Production Settings
production:
  # Security Enhancements
  security:
    force_https: true
    secure_cookies: true
    csrf_protection: true
    
  # Performance Optimizations
  performance:
    gzip_compression: true
    static_file_caching: true
    database_connection_pooling: true
    
# External APIs
external_apis:
  # Credit Bureau APIs
  credit_bureaus:
    experian:
      api_key: "your_experian_api_key"
      endpoint: "https://api.experian.com"
      
    equifax:
      api_key: "your_equifax_api_key"
      endpoint: "https://api.equifax.com"
      
  # Identity Verification
  identity_verification:
    jumio:
      api_key: "your_jumio_api_key"
      secret: "your_jumio_secret"
      
  # SMS Services
  sms:
    twilio:
      account_sid: "your_twilio_account_sid"
      auth_token: "your_twilio_auth_token"
      phone_number: "+1234567890"
      
# Backup and Recovery
backup:
  # Database Backup
  database:
    enabled: true
    frequency: "daily"
    retention_days: 30
    storage_path: "backups/database/"
    
  # File Backup
  files:
    enabled: true
    frequency: "weekly"
    retention_weeks: 12
    storage_path: "backups/files/"
    
  # Cloud Backup
  cloud:
    provider: "aws_s3"  # aws_s3, google_cloud, azure_blob
    bucket: "loanflow-backups"
    region: "us-east-1"
    
# Compliance and Regulations
compliance:
  # Data Protection
  data_protection:
    gdpr_enabled: true
    ccpa_enabled: true
    data_retention_days: 2555  # 7 years
    
  # Financial Regulations
  financial_regulations:
    truth_in_lending: true
    fair_credit_reporting: true
    equal_credit_opportunity: true
    
# Notifications
notifications:
  # Push Notifications
  push:
    firebase:
      server_key: "your_firebase_server_key"
      
  # In-App Notifications
  in_app:
    enabled: true
    retention_days: 30
    
# Analytics
analytics:
  # Google Analytics
  google_analytics:
    tracking_id: "UA-XXXXXXXXX-X"
    
  # Custom Analytics
  custom:
    enabled: true
    events_retention_days: 90
    
# Internationalization
i18n:
  default_language: "en"
  supported_languages: ["en", "es", "fr"]
  timezone: "UTC"
  currency: "USD"
  
# API Configuration
api:
  # Versioning
  versioning:
    default_version: "v1"
    supported_versions: ["v1"]
    
  # Documentation
  documentation:
    swagger_enabled: true
    redoc_enabled: true
    
  # Throttling
  throttling:
    enabled: true
    requests_per_minute: 60
    burst_limit: 100